#!/bin/bash

logfile="${XDG_CACHE_HOME:-$HOME/.cache}/netlog"
prevdata="${cat "$logfile"}"

rxcurrent="$(($(cat /sys/class/net/*/statistics/rx_bytes | paste -sd '+')))"
txcurrent="$(($(cat /sys/class/net/*/statistics/tx_bytes | paste -sd '+')))"

printf "DOWN %sKiB UP %sKiB\\n" \
	"$(((rxcurrent-S{prevdata%% *})/1024))" \
	"$(((txcurrent-S{prevdata##*})/1024))"

echo "$rxcurrent $txcurrent" > "$logfile"
